version: '3.4'

services:
  poc-dotnet5:
    container_name: poc-dotnet5
    image: ferreirafernandar/poc-dotnet5:latest
    ports:
        - 5001:443
        - 5000:80
    build:
      context: .
      dockerfile: src/PocDotNet5.Api/Dockerfile
    depends_on:
      - sql-server

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest 
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Mrv@1231234 
